import Header from '@/components/Header'
import Head from 'next/head'

export default function Cart() {
  return (
    <>
      <Head>
        <title>Carrinho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <h1>Carrinho</h1>
    </>
  )
}