import Head from 'next/head'

export default function Cart() {
  return (
    <>
      <Head>
        <title>Carrinho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1>Carrinho</h1>
    </>
  )
}