import Header from '@/components/Header'
import Head from 'next/head'
import Link from 'next/link'
import { Button, Container } from 'react-bootstrap'

export default function Home() {
  return (
    <>
      <Head>
        <title>Tech Shop | Seus eletrônicos preferidos com o melhor preço!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Container className='py-5 text-center'>
          <h1 className='mt-5 display-1'>
            Tech Shop
          </h1>
          <p className='my-4 display-6'>
            Encontre aqui seus eletrônicos preferidos com o melhor preço!
          </p>
          <Link href="/products">
            <Button className='px-4 pb-2'>
              Conheça nossos produtos
            </Button>
          </Link>
        </Container>
      </main>
    </>
  )
}
