import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Bem vindo ao Projeto <a href="https://nextjs.org">Next.js</a>
        </h1>

        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae porro debitis commodi earum quam labore voluptatem aperiam eligendi cupiditate iste. Incidunt, qui odit dolorem commodi laudantium fugit consequuntur ab. Ea.
        </p>
      </main>
    </>
  )
}
