import Header from '@/components/Header'
import ProductsList from '@/components/ProductsList'
import { ProductType, fetchProducts } from '@/components/services/products'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import { ReactNode } from 'react'
import { Container } from 'react-bootstrap'

export const getStaticProps: GetStaticProps = async () => {
  const products = await fetchProducts()
  return { props: { products } }
}

export default function Products(props: {
  children?: ReactNode
  products?: ProductType[]
}) {
  return (
    <>
      <Head>
        <title>Produtos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Container className='mb-5'>
          <h1 className='my-5'>Nossos produtos</h1>

          {<ProductsList products={props.products!} />}
        </Container>
      </main>
    </>
  )
}