import Header from '@/components/Header'
import Head from 'next/head'

export default function Products() {
  return (
    <>
      <Head>
        <title>Produtos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <h1>Nossos produtos</h1>
    </>
  )
}