import Header from "@/components/Header";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Button, Col, Container, FloatingLabel, Form, Row } from "react-bootstrap";

export default function Register() {
  return (
    <>
      <Head>
        <title>Tech Shop - Registre-se</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Container className="mt-5 border rounded p-5 shadow d-flex flex-column align-items-center" style={{ maxWidth: '50rem' }} >
          <Image src='/new-user-icon.png' alt='ícone novo usuário' width={50} height={50}></Image>
          <h2 className="text-center my-5">Para criar sua conta<br />Informe seus dados abaixo!</h2>
          <Form>
            <Row>
              <Col>
                <FloatingLabel className="mb-3" controlId="floatingName" label="Nome*">
                  <Form.Control type="text" placeholder="Insira seu nome" required />
                </FloatingLabel>
              </Col>
              <Col>
                <FloatingLabel className="mb-3" controlId="floatingLastname" label="Sobrenome*">
                  <Form.Control type="text" placeholder="Insira seu sobrenome" required />
                </FloatingLabel>
              </Col>
            </Row>
            <Row>
              <Col>
                <FloatingLabel className="mb-3" controlId="floatingCpf" label="CPF*">
                  <Form.Control type="number" min={11} max={11} placeholder="Insira seu CPF" required />
                </FloatingLabel>
              </Col>
              <Col>
                <FloatingLabel className="mb-3" controlId="floatingRg" label="RG">
                  <Form.Control type="number" placeholder="Insira seu RG" />
                </FloatingLabel>
              </Col>
            </Row>

            <FloatingLabel className="mb-3" controlId="floatingInput" label="E-mail*">
              <Form.Control type="email" placeholder="Insira seu email" required />
            </FloatingLabel>

            <FloatingLabel className="mb-3" controlId="floatingPassword" label="Senha*">
              <Form.Control type="password" placeholder="Senha" required />
            </FloatingLabel>

            <Button variant="primary" type="submit">
              Criar minha conta
            </Button>

            <Link className="px-3 text-decoration-none" href='/login'>
              Voltar para o login
            </Link>
          </Form>
        </Container >
      </main >

    </>
  )
}